baseURL = 'https://akbyrd.dev'
languageCode = 'en-us'
title = 'akbyrd'

cleanDestinationDir = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
markup.goldmark.renderer.unsafe = true # allow html
markup.goldmark.parser.attribute.block = true
markup.goldmark.parser.wrapStandAloneImageWithinParagraph = false
markup.highlight.lineNos = true
markup.highlight.noClasses = false

# Disable unnecessary RSS files
outputs.home = ['html']
outputs.taxonomy = ['html']
outputs.term = ['html']

params.social.twitter = 'abyrd89'

# Remove the folder and numeric prefix from page URLs
permalinks.posts = '/:slug/'
permalinks.tests = '/:slug/'

# Disable potential tracking and cookies
privacy.disqus.disable = true
privacy.googleAnalytics.anonymizeIP = true
privacy.googleAnalytics.disable = true
privacy.googleAnalytics.respectDoNotTrack = true
privacy.instagram.disable = true
privacy.instagram.simple = true
privacy.twitter.disable = true
privacy.twitter.simple = true
privacy.twitter.enableDNT = true
privacy.vimeo.disable = true
privacy.vimeo.enableDNT = true
privacy.youtube.disable = true
privacy.youtube.privacyEnhanced = true

services.rss.limit = -1

# Disable default taxonomies (category, series, and tag)
taxonomies = {}
