baseURL = 'https://akbyrd.dev'
languageCode = 'en-us'
title = 'akbyrd'
theme = 'PaperMod'

cleanDestinationDir = true
enableEmoji = true
enableGitInfo = true
#enableInlineShortcodes = true

markup.goldmark.renderer.hardWraps = true
markup.highlight.anchorLineNos = true
markup.highlight.lineNos = true
markup.highlight.lineNumbersInTable = false
