baseURL = 'https://akbyrd.dev'
languageCode = 'en-us'
title = 'akbyrd'

cleanDestinationDir = true
disableHugoGeneratorInject = true
disableKinds = ['RSS']
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
markup.goldmark.renderer.unsafe = true # allow html
markup.goldmark.parser.attribute.block = true
markup.goldmark.parser.wrapStandAloneImageWithinParagraph = false
markup.highlight.noClasses = false

# Add Atom output format
mediaTypes.'application/atom+xml'.suffixes = ['xml']
outputFormats.atom.baseName = 'feed'
outputFormats.atom.mediaType = 'application/atom+xml'
outputFormats.atom.permalinkable = true

params.social.twitter = 'abyrd89'

# Disable potential tracking and cookies
privacy.disqus.disable = true
privacy.googleAnalytics.anonymizeIP = true
privacy.googleAnalytics.disable = true
privacy.googleAnalytics.respectDoNotTrack = true
privacy.instagram.disable = true
privacy.instagram.simple = true
privacy.twitter.disable = true
privacy.twitter.simple = true
privacy.twitter.enableDNT = true
privacy.vimeo.disable = true
privacy.vimeo.enableDNT = true
privacy.youtube.disable = true
privacy.youtube.privacyEnhanced = true

# Disable default taxonomies (category, series, and tag)
taxonomies = {}
