name: Build and Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: none

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Hugo
        env:
          HUGO_VERSION: 0.136.4
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build Site
        run: hugo --environment production --minify

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Site
        id: deployment
        uses: actions/deploy-pages@v4
